---
- name: Create application directories
  file:
    state: directory
    path: '{{ item }}'
    mode: 'u=rwx,g=rwxs,o=rx'
    owner: '{{ rails__deploy_user }}'
    group: '{{ rails__group }}'
  with_items:
    - '{{ rails__root_dir }}'
    - '{{ rails__root_dir }}/shared'
    - '{{ rails__root_dir }}/shared/config'
