---
- name: Validate variables
  action: validate_vars

- include_tasks: system.yml
- include_tasks: yarn.yml
- include_tasks: rvm_gemset.yml
- include_tasks: bundler.yml
- include_tasks: services.yml
