---
- name: Install system packages
  apt:
    update_cache: true
    name:
      - build-essential
      - gnupg2
      - liblzma-dev
      - libpq-dev
      - patch
      - zlib1g-dev

- name: Create RVM gemset
  shell: "/bin/bash --login -c 'rvm use ruby-2.6.2@partynest --create'"
  register: partynest__gemset_result
  changed_when: >-
    "partynest__gemset_result.stdout is search('ruby-2.6.2 - #gemset created ')"
