---
- name: Install system packages
  apt:
    update_cache: true
    name:
      - build-essential
      - gnupg2
      - liblzma-dev
      - libpq-dev
      - patch
      - zlib1g-dev

- name: Create RVM gemset
  shell: "/bin/bash --login -c 'rvm use ruby-2.6.2@partynest --create'"
  register: partynest__gemset_result
  changed_when: >-
    "partynest__gemset_result.stdout is search('ruby-2.6.2 - #gemset created ')"

- name: Check Bundler
  shell: >
    /bin/bash --login -c
    "rvm ruby-2.6.2@partynest do
    gem info bundler --installed --version '~>2.0'"
    || true
  register: partynest__bundler_result
  changed_when: false

- name: Install Bundler
  shell: >
    /bin/bash --login -c
    "rvm ruby-2.6.2@partynest do
    gem install bundler -v '~> 2.0'"
  when: "partynest__bundler_result.stdout is search('false')"

- name: Create system group
  group:
    name: '{{ partynest__group }}'
    system: true

- name: Create system user
  user:
    name: '{{ partynest__user }}'
    group: '{{ partynest__group }}'
    system: true
    create_home: false

- name: Create application directories
  file:
    state: directory
    path: '{{ item }}'
    mode: 'u=rwx,g=rwxs,o=rx'
    owner: '{{ partynest__deploy_user }}'
    group: '{{ partynest__group }}'
  with_items:
    - '{{ partynest__root_dir }}'
    - '{{ partynest__root_dir }}/shared'
    - '{{ partynest__root_dir }}/shared/config'
