---
- name: Validate variables
  action: validate_vars

- name: Add Yarn APT key
  apt_key:
    id: 72ECF46A56B4AD39C907BBB71646B01B86E50310
    url: https://dl.yarnpkg.com/debian/pubkey.gpg

- name: Add Yarn APT repository
  copy:
    dest: /etc/apt/sources.list.d/yarn.list
    mode: 'u=rw,g=r,o=r'
    owner: root
    group: root
    content: 'deb https://dl.yarnpkg.com/debian/ stable main'

- name: Install system packages
  apt:
    cache_valid_time: 0
    name:
      - build-essential
      - liblzma-dev
      - libpq-dev
      - patch
      - postgresql-client
      - yarn
      - zlib1g-dev

- name: Create RVM gemset
  shell: >
    /bin/bash --login -c "{{ rails__rvm }} use {{ rails__ruby }}@{{ rails__gemset }} --create"
  register: rails__gemset_result
  changed_when: >-
    "rails__gemset_result.stdout is search(rails__ruby + ' - #gemset created ')"

- name: Check Bundler
  shell: >
    /bin/bash --login -c
    "{{ rails__rvm_do }} gem info bundler --installed --version '~> 2.0'"
    || true
  register: rails__bundler_result
  changed_when: false

- name: Install Bundler
  shell: >
    /bin/bash --login -c
    "{{ rails__rvm_do }} gem install bundler -v '~> 2.0'"
  when: "rails__bundler_result.stdout is search('false')"

- name: Create system group
  group:
    name: '{{ rails__group }}'
    system: true

- name: Create system user
  user:
    name: '{{ rails__user }}'
    group: '{{ rails__group }}'
    system: true
    create_home: false

- name: Create application directories
  file:
    state: directory
    path: '{{ item }}'
    mode: 'u=rwx,g=rwxs,o=rx'
    owner: '{{ rails__deploy_user }}'
    group: '{{ rails__group }}'
  with_items:
    - '{{ rails__root_dir }}'
    - '{{ rails__root_dir }}/shared'
    - '{{ rails__root_dir }}/shared/config'

- name: Create general service
  template:
    src: templates/rails.service
    dest: '/etc/systemd/system/{{ rails__service }}.service'
    mode: 'u=rw,g=r,o=r'
    owner: root
    group: root
  notify: rails | Update general service

- name: Create restart service
  template:
    src: templates/rails-restart.service
    dest: '/etc/systemd/system/{{ rails__service }}-restart.service'
    mode: 'u=rw,g=r,o=r'
    owner: root
    group: root
  notify: rails | Update restarter service

- name: Create restart path
  template:
    src: templates/rails-restart.path
    dest: '/etc/systemd/system/{{ rails__service }}-restart.path'
    mode: 'u=rw,g=r,o=r'
    owner: root
    group: root
  notify: rails | Update restarter path

- name: Create Puma service
  template:
    src: templates/rails-puma.service
    dest: '/etc/systemd/system/{{ rails__service }}-puma.service'
    mode: 'u=rw,g=r,o=r'
    owner: root
    group: root
  notify: rails | Update Puma service

- name: Create Sidekiq service
  template:
    src: templates/rails-sidekiq.service
    dest: '/etc/systemd/system/{{ rails__service }}-sidekiq.service'
    mode: 'u=rw,g=r,o=r'
    owner: root
    group: root
  notify: rails | Update Sidekiq service
