---
- name: Validate variables
  action: validate_vars

- name: Install system packages
  apt:
    update_cache: true
    name:
      - build-essential
      - gnupg2
      - liblzma-dev
      - libpq-dev
      - patch
      - zlib1g-dev

- name: Create RVM gemset
  shell: "/bin/bash --login -c 'rvm use ruby-2.6.2@partynest --create'"
  register: partynest__gemset_result
  changed_when: >-
    "partynest__gemset_result.stdout is search('ruby-2.6.2 - #gemset created ')"

- name: Check Bundler
  shell: >
    /bin/bash --login -c
    "rvm ruby-2.6.2@partynest do
    gem info bundler --installed --version '~> 2.0'"
    || true
  register: partynest__bundler_result
  changed_when: false

- name: Install Bundler
  shell: >
    /bin/bash --login -c
    "rvm ruby-2.6.2@partynest do
    gem install bundler -v '~> 2.0'"
  when: "partynest__bundler_result.stdout is search('false')"

- name: Create system group
  group:
    name: '{{ partynest__group }}'
    system: true

- name: Create system user
  user:
    name: '{{ partynest__user }}'
    group: '{{ partynest__group }}'
    system: true
    create_home: false

- name: Create application directories
  file:
    state: directory
    path: '{{ item }}'
    mode: 'u=rwx,g=rwxs,o=rx'
    owner: '{{ partynest__deploy_user }}'
    group: '{{ partynest__group }}'
  with_items:
    - '{{ partynest__root_dir }}'
    - '{{ partynest__root_dir }}/shared'
    - '{{ partynest__root_dir }}/shared/config'

- name: Create general service
  template:
    src: templates/partynest.service
    dest: '/etc/systemd/system/{{ partynest__service }}.service'
    mode: 'u=rw,g=r,o=r'
    owner: root
    group: root
  notify: Update Partynest general service

- name: Create restart service
  template:
    src: templates/partynest-restart.service
    dest: '/etc/systemd/system/{{ partynest__service }}-restart.service'
    mode: 'u=rw,g=r,o=r'
    owner: root
    group: root
  notify: Update Partynest restarter service

- name: Create restart path
  template:
    src: templates/partynest-restart.path
    dest: '/etc/systemd/system/{{ partynest__service }}-restart.path'
    mode: 'u=rw,g=r,o=r'
    owner: root
    group: root
  notify: Update Partynest restarter path

- name: Create web service
  template:
    src: templates/partynest-web.service
    dest: '/etc/systemd/system/{{ partynest__service }}-web.service'
    mode: 'u=rw,g=r,o=r'
    owner: root
    group: root
  notify: Update Partynest web service

- name: Create worker service
  template:
    src: templates/partynest-worker.service
    dest: '/etc/systemd/system/{{ partynest__service }}-worker.service'
    mode: 'u=rw,g=r,o=r'
    owner: root
    group: root
  notify: Update Partynest worker service
