---
- name: Install system packages
  apt:
    update_cache: true
    name:
      - apt-transport-https
      - build-essential
      - liblzma-dev
      - libpq-dev
      - patch
      - postgresql-client
      - zlib1g-dev

- name: Create system group
  group:
    name: '{{ rails__group }}'
    system: true

- name: Create system user
  user:
    name: '{{ rails__user }}'
    group: '{{ rails__group }}'
    system: true
    create_home: false

- name: Create application directories
  file:
    state: directory
    path: '{{ item }}'
    mode: 'u=rwx,g=rwxs,o=rx'
    owner: '{{ rails__deploy_user }}'
    group: '{{ rails__group }}'
  with_items:
    - '{{ rails__root_dir }}'
    - '{{ rails__root_dir }}/shared'
    - '{{ rails__root_dir }}/shared/config'

- name: Create application environment file
  template:
    src: templates/environment
    dest: '{{ rails__root_dir }}/environment'
    mode: 'u=rw,g=r,o='
    owner: '{{ rails__deploy_user }}'
    group: '{{ rails__group }}'
