---
- name: rails | Update general service
  systemd:
    daemon_reload: true
    name: '{{ rails__service }}.service'
    enabled: true

- name: rails | Update restarter service
  systemd:
    daemon_reload: true
    name: '{{ rails__service }}-restart.service'
    enabled: false

- name: rails | Update restarter path
  systemd:
    daemon_reload: true
    name: '{{ rails__service }}-restart.path'
    enabled: true
    state: restarted

- name: rails | Update Puma service
  systemd:
    daemon_reload: true
    name: '{{ rails__service }}-puma.service'
    enabled: true

- name: rails | Update Sidekiq service
  systemd:
    daemon_reload: true
    name: '{{ rails__service }}-sidekiq.service'
    enabled: true
