---
- name: partynest | Update Partynest general service
  systemd:
    daemon_reload: true
    name: '{{ partynest__service }}.service'
    enabled: true

- name: partynest | Update Partynest restarter service
  systemd:
    daemon_reload: true
    name: '{{ partynest__service }}-restart.service'
    enabled: false

- name: partynest | Update Partynest restarter path
  systemd:
    daemon_reload: true
    name: '{{ partynest__service }}-restart.path'
    enabled: true
    state: restarted

- name: partynest | Update Partynest web service
  systemd:
    daemon_reload: true
    name: '{{ partynest__service }}-web.service'
    enabled: true

- name: partynest | Update Partynest worker service
  systemd:
    daemon_reload: true
    name: '{{ partynest__service }}-worker.service'
    enabled: true
