---
- name: Converge
  hosts: all
  become: true
  module_defaults:
    apt:
      force_apt_get: true
      cache_valid_time: 86400
  roles:
    - role: rails
      vars:
        rails__env_vars:
          FOO1: 123
          _BAR: car
          c_1d: baz
